export const requestSeed = [
  ["REQ-01", "Aditi Sharma", "aditi.sharma@veridian-corp.example", "2026-09-21", "My laptop won't turn on at all, it's completely dead, had it about 3.5 years", "Not started"],
  ["REQ-02", "Vikram Chawla", "vikram.chawla@veridian-corp.example", "2026-09-21", "Can I get Wi-Fi access for a guest visiting our office?", "Not started"],
  ["REQ-03", "Karan Mehta", "karan.mehta@veridian-corp.example", "2026-09-21", "I'm locked out of my account, tried my password 6 times.", "In progress — reset queued"],
  ["REQ-04", "Ritu Bhatia", "ritu.bhatia@veridian-corp.example", "2026-09-22", "Need approval to install a data-analysis tool that's not in the software catalog.", "Waiting on Security review"],
  ["REQ-05", "Sanjay Oberoi", "sanjay.oberoi@veridian-corp.example", "2026-09-22", "My VPN stopped working this morning, credentials expired.", "Not started"],
  ["REQ-06", "Meera Iyer", "meera.iyer@veridian-corp.example", "2026-09-22", "Printer on the 3rd floor keeps showing 'paper jam' even though there's no jam.", "Investigating — technician assigned"],
  ["REQ-07", "Farhan Ali", "farhan.ali@veridian-corp.example", "2026-09-23", "I've started working from home 4 days a week, how do I get a monitor?", "Not started"],
  ["REQ-08", "Ananya Reddy", "ananya.reddy@veridian-corp.example", "2026-09-23", "I think I got a phishing email asking for my login — forwarding it to a few teammates to check.", "Escalated to Security (auto-flagged)"],
  ["REQ-09", "Rohit Desai", "rohit.desai@veridian-corp.example", "2026-09-23", "My mailbox is full and I can't send emails.", "Not started"],
  ["REQ-10", "Kavya Pillai", "kavya.pillai@veridian-corp.example", "2026-09-23", "Can someone give me admin access to the finance reporting server? Need it urgently for month-end.", "Not started"],
  ["REQ-11", "Nikhil Bansal", "nikhil.bansal@veridian-corp.example", "2026-09-24", "New contractor joining my team next week, they'll need VPN access.", "Not started"],
  ["REQ-12", "Sneha Kulkarni", "sneha.kulkarni@veridian-corp.example", "2026-09-24", "I can't log into the expense tool, keeps saying invalid credentials.", "Waiting on employee response (asked for a screenshot, no reply yet)"],
  ["REQ-13", "Aman Gupta", "aman.gupta@veridian-corp.example", "2026-09-24", "Laptop screen is flickering and off, had it 2 years, might just need a fix not a replacement.", "Not started"],
  ["REQ-14", "Tanya Chopra", "tanya.chopra@veridian-corp.example", "2026-09-25", "Requesting approval to install a browser extension for productivity tracking.", "Not started"],
  ["REQ-15", "Rahul Menon", "rahul.menon@veridian-corp.example", "2026-09-25", "hey can you help, its not working", "Not started"],
] as const;

export const kbSeed = [
  ["KB-01", "Password Reset", "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required.", "password"],
  ["KB-02", "VPN Access", "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee.", "vpn"],
  ["KB-03", "Laptop Replacement", "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement.", "laptop"],
  ["KB-04", "Software Installation Requests", "Standard software listed in the approved catalog can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days.", "software"],
  ["KB-05", "Printer Troubleshooting", "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag.", "printer"],
  ["KB-06", "Email Mailbox Quota", "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB.", "mailbox"],
  ["KB-07", "Guest Wi-Fi Access", "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required.", "wifi"],
  ["KB-08", "Expense Software Access", "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists.", "expense_tool"],
  ["KB-09", "Security Incident Reporting", "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees.", "phishing"],
  ["KB-10", "Work-From-Home Equipment", "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved.", "wfh_equipment"],
  ["ASSET-POLICY", "Asset Management Policy", "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval.", "asset_management"],
] as const;

export const legacyTicketSeed = [
  ["TK-1042", "REQ-05", "vpn", "VPN credential expired", "medium", "RESOLVED", "IT Helpdesk", "resolve", "KB-02"],
  ["TK-1043", "REQ-01", "laptop", "Laptop replacement (3.2 yrs old)", "high", "IN_PROGRESS", "IT Asset Management", "fulfill", "KB-03, ASSET-POLICY"],
  ["TK-1044", "REQ-04", "software", "Non-catalog software request", "medium", "HUMAN_REVIEW", "IT Security Review", "route", "KB-04"],
  ["TK-1045", "REQ-09", "mailbox", "Mailbox quota increase", "medium", "RESOLVED", "IT Helpdesk", "approved_35gb", "KB-06"],
  ["TK-1046", "REQ-06", "printer", "Printer jam, floor 2", "low", "RESOLVED", "IT Helpdesk", "resolve", "KB-05"],
  ["TK-1047", "REQ-07", "wfh_equipment", "Home office equipment request", "medium", "HUMAN_REVIEW", "Finance", "pending_finance", "KB-10"],
  ["TK-1048", "REQ-08", "phishing", "Phishing email reported", "critical", "ESCALATED", "Security Team", "escalate", "KB-09"],
  ["TK-1049", "REQ-03", "password", "Password reset", "low", "RESOLVED", "IT Helpdesk", "resolve", "KB-01"],
  ["TK-1050", "REQ-10", "admin_access", "Admin access request", "critical", "REJECTED", "Security Team", "reject", "KB-09"],
  ["TK-1051", "REQ-02", "wifi", "Guest Wi-Fi issued", "low", "RESOLVED", "Front Desk Kiosk", "self_service", "KB-07"],
] as const;
